_target_: src.models.networks.masking.RandomMasker
_partial_: true
proba_monodate: 0.1
fraction_drop_time: 0.5
alpha_drop_channel: 5 #0.8 # proba of dropping a channel 1/(1 + math.sqrt(alpha_channel/C))
crop_percentage_axes: 1.0 # extract a square
fraction_drop_spatial: 0.75 # drop random token inside the square
mask_C_with_blocks: 2
