defaults:
  - train_transform: Identity
  - test_transform: Identity
  - _self_

name: EnmapTreemap
global_batch_size: 1
num_classes: 24
height: 128
width: 128
num_patches: 16384
norm_path: ${paths.data_dir}/SpectralEarthEval/enmap_treemap/
task : segmentation # "classification" or "segmentation"
is_multilabel : false # only for classification
res: 30
scale_base: 6
out_patch_size: 1
use_memmap: True
memmap_dir: ${paths.data_dir}

raw_mask: false
split_root: ${paths.data_dir}/SpectralEarthEval/splits/enmap_treemap/
classes: [0, 184, 185, 221, 924, 105, 503, 520, 706, 801, 201, 264, 266, 281, 301, 901, 406, 923, 142, 161, 602, 607, 608, 267, 371]

train_dataset:
  _partial_: true
  _target_: data.EnmapDataset.EnMAPDataset
  path: ${paths.data_dir}/SpectralEarthEval/enmap_treemap/
  product: enmap_treemap
  mask_root: treemap
  split: train
  transform: ${dataset.train_transform}
  classes: ${dataset.classes}
  raw_mask: ${dataset.raw_mask}
  split_root: ${dataset.split_root}
  norm_path: ${dataset.norm_path}

val_dataset:
  _partial_: true
  _target_: data.EnmapDataset.EnMAPDataset
  path: ${paths.data_dir}/SpectralEarthEval/enmap_treemap/
  product: enmap_treemap
  mask_root: treemap
  split: val
  transform: ${dataset.test_transform}
  classes: ${dataset.classes}
  raw_mask: ${dataset.raw_mask}
  split_root: ${dataset.split_root}
  norm_path: ${dataset.norm_path}

test_dataset:
  _partial_: true
  _target_: data.EnmapDataset.EnMAPDataset
  path: ${paths.data_dir}/SpectralEarthEval/enmap_treemap/
  product: enmap_treemap
  mask_root: treemap
  split: test
  transform: ${dataset.test_transform}
  classes: ${dataset.classes}
  raw_mask: ${dataset.raw_mask}
  split_root: ${dataset.split_root}
  norm_path: ${dataset.norm_path}
