defaults:
  - train_transform: Identity
  - test_transform: Identity
  - _self_

name: EnmapNlcd
global_batch_size: 1
num_classes: 15
height: 128
width: 128
num_patches: 16384
norm_path: ${paths.data_dir}/SpectralEarthEval/enmap_nlcd/
task : segmentation # "classification" or "segmentation"
is_multilabel : false # only for classification
res: 30
scale_base: 6
out_patch_size: 1
use_memmap: True
memmap_dir: ${paths.data_dir}

raw_mask: false
split_root: ${paths.data_dir}/SpectralEarthEval/splits/enmap_nlcd/
classes: [0, 11, 21, 22, 23, 24, 31, 41, 42, 43, 52, 71, 81, 82, 90, 95]

train_dataset:
  _partial_: true
  _target_: data.EnmapDataset.EnMAPDataset
  path: ${paths.data_dir}/SpectralEarthEval/enmap_nlcd/
  product: enmap_nlcd
  mask_root: nlcd
  split: train
  transform: ${dataset.train_transform}
  classes: ${dataset.classes}
  raw_mask: ${dataset.raw_mask}
  split_root: ${dataset.split_root}
  norm_path: ${dataset.norm_path}

val_dataset:
  _partial_: true
  _target_: data.EnmapDataset.EnMAPDataset
  path: ${paths.data_dir}/SpectralEarthEval/enmap_nlcd/
  product: enmap_nlcd
  mask_root: nlcd
  split: val
  transform: ${dataset.test_transform}
  classes: ${dataset.classes}
  raw_mask: ${dataset.raw_mask}
  split_root: ${dataset.split_root}
  norm_path: ${dataset.norm_path}

test_dataset:
  _partial_: true
  _target_: data.EnmapDataset.EnMAPDataset
  path: ${paths.data_dir}/SpectralEarthEval/enmap_nlcd/
  product: enmap_nlcd
  mask_root: nlcd
  split: test
  transform: ${dataset.test_transform}
  classes: ${dataset.classes}
  raw_mask: ${dataset.raw_mask}
  split_root: ${dataset.split_root}
  norm_path: ${dataset.norm_path}
