defaults:
  - train_transform: Identity
  - test_transform: Identity
  - _self_

name: PASTIS-R
global_batch_size: 1
num_classes: 20
nb_split: 1
height: 128
width: 128
num_patches: 16384
classif: False
len: 1455
norm_path: ${paths.data_dir}/PASTIS-R/

temporal_dropout: 200
res: 10
out_patch_size: 1
scale_base: 4
task : segmentation # "classification" or "segmentation"
is_multilabel : false # only for classification

modalities:
  - "s2"
  - "s1"

train_dataset:
  _partial_: true
  _target_: data.Pastis.PASTIS
  path: ${paths.data_dir}/PASTIS-R/
  modalities: ${dataset.modalities}
  transform: ${dataset.train_transform}
  reference_date: "2018-01-01" #"2018-09-01"
  folds: [1, 2, 3]
  nb_split: ${dataset.nb_split}
  classif: ${dataset.classif}
  norm_path: ${dataset.norm_path}
  split: train
  temporal_dropout: ${dataset.temporal_dropout}

val_dataset:
  _partial_: true
  _target_: data.Pastis.PASTIS
  path: ${paths.data_dir}/PASTIS-R/
  modalities: ${dataset.modalities}
  transform: ${dataset.test_transform}
  reference_date: "2018-01-01" #"2018-09-01"
  folds: [4]
  nb_split: ${dataset.nb_split}
  classif: ${dataset.classif}
  norm_path: ${dataset.norm_path}
  split: val
  temporal_dropout: ${dataset.temporal_dropout}

test_dataset:
  _partial_: true
  _target_: data.Pastis.PASTIS
  path: ${paths.data_dir}/PASTIS-R/
  modalities: ${dataset.modalities}
  transform: ${dataset.test_transform}
  reference_date: "2018-01-01" #"2018-09-01"
  folds: [5]
  nb_split: ${dataset.nb_split}
  classif: ${dataset.classif}
  norm_path: ${dataset.norm_path}
  split: test
